language: r

r:
  - oldrel
  - release
  - devel
  
pandoc_version: 1.19.2.1

apt_packages: libxml2-dev

r_binary_packages: abbyyr

r_packages: stats

bioc_packages: BiocVersion

r_github_packages: r-lib/devtools
