name: valet-travis-languages-testing/r-example
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: "${{ matrix.r }}"
    - run: R -e 'remotes::install_deps(dep = T)'
    - run: R CMD build . ; R CMD check *tar.gz --as-cran
    strategy:
      matrix:
        r:
        - 3.5.3
        - release
